# fixing inclusion/exclusion split based on edge case w/ multiple new lines within inclusion/exclusion criteria
x = ["INCLUSION CRITERIA:\n\n>= 18 years of age.\nWilling and able to complete a verbal telephone consent.\nWilling to undergo one blood draw or home blood sampling.\nWilling to have blood samples stored for future research.\n\nEXCLUSION CRITERIA:\n\nConfirmed history of COVID19 infection or exposure\nCurrent symptoms consistent with COVID19 infection\nAny condition or event that, in the PI s opinion, may substantially increase the risk associated with study participation or compromise the study's scientific objectives. Conditions that exclude a subject are considered to be unlikely, but an example would include having an acute respiratory infection or recent exposure that would prevent participants that would make it unsafe to obtain blood samples.\nNot willing to have blood samples stored for future research.",
"Inclusion Criteria:\n\nWomen with a self-reported live pregnancy >14 weeks\nPresently in the outpatient setting (i.e. not admitted to the hospital)\nTested positive for COVID-19 within last 7 days\nMust be living in Canada\n\nExclusion Criteria:\n\nKnown glucose-6-phosphate dehydrogenase (G6PD) deficiency\nKnown cardiac disease (or under investigation)\nCurrently taking medication contraindicated as per Health Canada list for hydroxychloroquine\nKnown retinopathy\nKnown hypersensitivity to 4-aminoquinoline compounds\nAlready taking hydroxychloroquine\nUnwilling to answer follow-up questionnaires\nCurrently in labor\nInpatient women at time of COVID-19 diagnosis.",
"Inclusion Criteria:\n\nHave undergone successful testing for Covid-19\nHave sufficient viral RNA remaining for research analysis following testing for Covid-19\n\nExclusion Criteria:\n\nInsufficient viral RNA remains following testing for Covid-19",
"Inclusion Criteria:\n\nARDS as defined by the Berlin definition.\n\nOnset within 1 week of identified insult.\nWithin the same 24-hour time period i. Hypoxic respiratory failure (PaO2/ FiO2 ratio ≤ 27kPa on PEEP ≥ 5 cmH20) ii. Bilateral infiltrates on chest X-ray consistent with pulmonary oedema not explained by another pulmonary pathology iii. Respiratory failure not fully explained by cardiac failure or fluid overload\nPatient is receiving invasive mechanical ventilation\nCOVID-19 based on clinical diagnosis or PCR result\n\nExclusion Criteria:\n\nMore than 72 hours from the onset of ARDS.\nAge < 16 years.\nPatient is known to be pregnant\nMajor trauma in the prior 5 days.\nPresence of any active malignancy (other than non-melanoma skin cancer) that required treatment within the last year.\nWHO Class III or IV pulmonary hypertension.\nVenous thromboembolism currently receiving anti-coagulation or within the past 3 months\nCurrently receiving extracorporeal life support (ECLS).\nSevere chronic liver disease with Child-Pugh score > 12.\nDNAR (Do Not Attempt Resuscitation) order in place.\nTreatment withdrawal imminent within 24 hours.\nConsent declined.\nPrisoners.\nNon-English speaking patients or those who do not adequately understand verbal or written information unless an interpreter is available.\nPreviously enrolled in the REALIST trial.",
"Inclusion Criteria:\n\nInformed consent from patient or legal representative.\nMale or female, aged ≥ 18 years;\nAcute respiratory distress syndrome; with imminent risk of death, and with chest CT scan with pulmonary impairment greater than 50%;\nConfirmed or pending diagnosis of COVID-19.\n\nExclusion Criteria:\n\nPleural effusion > 150mL or ascites > 200mL;\nChronic liver disease;\nALT and AST serum levels >= three times the upper limit of normality;\nRenal failure (dialysis)\nMultiple organ failure\n\n7. Concomitant use or use in the last 7 days of cell therapy with stem cells; 8. Any clinical or laboratory condition or comorbidity that, at medical discretion, 9. Known hypersensitivity to the investigational product; 10. Subject who is pregnant or lactating",
"Inclusion Criteria:\n\nAdults (age 18 years) considered as a case of COVID-19 disease with suspected DVT in lower and/or upper limbs: (i) A laboratory test confirming COVID-19 infection or (ii) a clinical diagnosis of COVID-19 infection (without any testing) is considered.\n\n- Suspected DVT:\n\nPatients with clinical data of suspected DVT\nand/or patients with analytical data on suspected DVT\nand/or patients with ultrasound data of suspected DVT\n\nExclusion Criteria:\n\n-",
"Inclusion Criteria:\n\nVolunteers who have understood and signed the informed consent;\nAge ≥18 years, gender unlimited;\n\nPatients diagnosed with acute severe 2019-nCoV pneumonia:\n\nLaboratory (RT-PCR) confirmed infection with 2019-nCoV.\nLung involvement confirmed with pulmonary CT scan.\nAt least one of the following conditions should be met: respiratory distress, RR ≥ 30 times/min; oxygen saturation ≤ 93% in resting state; PaO2/FiO2 ≤ 300mmHg; respiratory failure and mechanical ventilation are required; shock occurs; ICU monitoring and treatment is required in combination with other organ failure.\n\nExclusion Criteria:\n\nViral pneumonia with other viruses besides 2019-nCoV.\nPatients are not suitable for immunoglobulin therapy.\nParticipation in other studies.\nOther circumstances in which the investigator determined that the patient is not suitable for the clinical trial.",
"Inclusion Criteria:\n\nSubjects enrolled in the trial must meet all of the following criteria.\n\nConfirmed COVID-19 pneumonia\nHypoxia as defined by room air oxygen saturation less than 92% or supplemental oxygen requirement\nPresence of at least one additional biomarker that has been shown to predict poor prognosis: a) serum ferritin ≥500ug/l, b) LDH ≥250U/L, c) d-dimer ≥1ug/L, or d) lymphopenia as defined by absolute lymphocyte count <1,000/uL\nAge ≥ 18 years\nCompleted informed consent\n\nExclusion Criteria:\n\nSubjects who meet ANY of the following criteria are not eligible for enrollment as study participants:\n\nKnown allergy or hypersensitivity to sirolimus\nInability or refusal to provide informed consent\nAdvanced respiratory support (high flow oxygen ≥ 15 L/min, CPAP, non-invasive or invasive mechanical ventilation)\nActive enrollment in other interventional clinical drug trials. Co-enrollment in observational studies and biorepositories is allowed.\nPregnant women\nBreast feeding\nOn chronic immunosuppression for other medical conditions such as rheumatological disorders, inflammatory bowel disease, or in patients with organ transplants. A list of these medications is provided in Section 12.3.4\n\nAny clinically significant medical disease which in the opinion of the investigator precludes the patient from enrolling in the trial, including (but not limited to):\n\nHistory of liver cirrhosis\nEnd stage renal disease or need for renal replacement therapy\nDecompensated heart failure\nKnown active tuberculosis or history of incompletely treated tuberculosis\nUncontrolled systemic bacterial or fungal infections\nActive viral infection other than COVID-19",
"Inclusion Criteria:\n\nConfirmed diagnosis of COVID-19 by reverse transcription polymerase chain reaction (RT-PCR)\n\nNew admission to eligible CUIMC ICUs within 5 days\n\nTransfer from nonparticipating to participating ICU is eligible if otherwise meets eligibility criteria.\nPatients transferred between participating ICUs will maintain initial treatment assignment.\nPatients not on therapeutic anticoagulation and who were already admitted to participating ICU within 5 days of trial initiation are additionally eligible.\n\nExclusion Criteria:\n\nWeight under 50kg\n\nContraindication to anticoagulation in the opinion of the treating clinician including\n\novert bleeding\nplatelet count <50,000\nBleeding Academic Research Consortium (BARC) major bleeding in the past 30 days\nGastrointestinal (GI) bleeding within 3 months\nhistory of intracranial hemorrhage\nIschemic stroke within the past 2 weeks\ncraniotomy/major neurosurgery within the past 30 days\ncardiothoracic surgery within the past 30 days\nintra-abdominal surgery within 30 days prior to enrollment\nHead or spinal trauma in the last months\nHistory of uncorrected cerebral aneurysm or arteriovenous malformation (AVM)\nIntracranial malignancy\nPresence of an epidural or spinal catheter\nRecent major surgery within the last 14 days\nDecrease in hemoglobin >3 g/dL over the last 24 hours\nAllergic reaction to anticoagulants (e.g. Heparin Induced Thrombocytopenia) as documented in the electronic health records. Extracorporeal membrane oxygenation (ECMO) support or other mechanical circulatory support.\nSevere chronic liver dysfunction (history of portosystemic hypertension (HTN), esophageal varices, or Child-Pugh class C or above or similar Model For End-Stage Liver Disease (MELD) scores), abnormality in liver function tests (aspartate aminotransferase (AST), alanine aminotransferase (ALT), bilirubin) 5 times greater than upper normal limit.\nA history of congenital bleeding diatheses or anatomical anomaly that predisposes to hemorrhage (e.g. hemophilia, hereditary hemorrhagic telangiectasia)\nTreating physician preference for therapeutic anticoagulation\nEnrollment in other concurrent trials related to anticoagulant or antiplatelet therapy\nExisting treatment with therapeutic anticoagulation during the previous 7 days of hospitalization prior to ICU admission (e.g. for venous thromboembolism (VTE), atrial fibrillation, mechanical valve, etc).\nDo-not-resuscitate (DNR) /do-not-intubate (DNI) or comfort measures only (CMO) orders prior to randomization.",
"Inclusion criteria:\n\nMale or female≥ 18 years of age\nWritten informed consent of the patient or a proxy\nAbility for participant to comply with the requirements of the study\n\nHospitalized patient with COVID-19 defined as\n\nPositive SARS-CoV2 RT-PCR\nOr typical COVID-19 Radiographic infiltrates on the CT scan (peripheral ground glass without lung cavitation, lymphadenopathy, or pulmonary nodules) other non COVID-19 diagnosis ruled out.\n\nPatient with respiratory symptoms and requirement of oxygen therapy as defined:\n\nOxygen therapy >= 4L/min to maintain Sp02>92% and respiratory rate >=24/min.\nOr patients under oxygen >= 1L/min and presenting worsening of oxygen requirement defined by an increase of oxygen therapy >= 2L/min to maintain Sp02>92%.\nInflammatory component C-Reactive Protein ≥ 50mg/L.\nPatients within the first 20 days from the onset of the first COVID-19 symptoms\nProbabilistic antibiotics therapy according to local practice\n\nNon-inclusion criteria:\n\nRespiratory failure related to other cause than COVID-19\nPatients requiring mechanical ventilation at inclusion or requiring oxygen therapy equal or more than 11 liters per min to maintain Sp02>92%\nInfectious diseases such as severe bacterial infections, aspergillosis, HIV, active HCV, active HBV, active tuberculosis\n\nContra indication to anti-IL1 receptor\n\nKnown hypersensitivity to Anakinra\nAbsolute neutrophil count (ANC)< 1500/mm3\nLiver cirrhosis Child-Pugh Score C\nLive or attenuated vaccine in the past 8 weeks\nPregnant or breast-feeding women\nPatients with either legally protected status or who have been deprived of their freedom\nPatient included in other interventional therapeutic research (e.g. = concurrent participation in French CoVID-19 is accepted)\nPatients who have received previous treatment by anti-IL6R, anti-IL-6, anti-IL1R, anti-IL1 or anti-TNFα within 21 days preceding inclusion\nAbsence of Health Insurance\nExistence of any life-threatening co-morbidity or any other medical condition which,in the opinion of the investigator, makes the patient unsuitable for inclusion.",
"INCLUSION CRITERIA (NOT APPLICABLE TO COVID COHORT):\n\nParticipants will be eligible if they:\n\nHave a diagnosis of uveitis, scleritis or a disease known to be associated with intraocular inflammation, (e.g., sarcoidosis, Behcet's disease, multiple sclerosis (MS) and lymphoma) OR could serve as an unaffected control.\nAre eight years of age or older if an affected participant.\nAre 18 years of age or older if serving as an unaffected control.\n\nFor participants 18 years of age and older:\n\nAre willing to give informed consent that includes collection and study of at least one peripheral blood sample.\n\nEXCLUSION CRITERIA (NOT APPLICABLE TO COVID COHORT):\n\nParticipants will not be eligible if they:\n\nAre unable to understand and sign the informed consent form.\nAre unable or unwilling to give informed consent that includes use of medical records and clinical samples for current and future research related to vision and diseases affecting the eyes.\nHave a systemic disease that compromises the ability to provide adequate ophthalmologic examination or treatment as determined by the investigator.\n\nFor participants with uveitis:\n\nHave inactive anterior uveitis or quiescent infectious uveitis not requiring such regimented and intensive standardized testing as determined by the Investigator.\nHave end stage or chronic quiescent changes in the setting of an established infectious etiology, such as an old ocular toxoplasma scar (participants with active intraocular inflammation due to infection will be recruited).\n\nThe eligibility requirements for this protocol are intended to be broadly inclusive, but those individuals screened at the NEI and found to be ineligible may be evaluated under the NEI Screening Protocol for potential participation in other studies.\n\nINCLUSION CRITERIA FOR COVID-19 COHORT:\n\nParticipants with COVID-19 will be eligible if they:\n\nHave a diagnosis of COVID-19 confirmed by a nasaopharyngeal swab (or another confirmative test) within less than or equal to 3 days prior, with symptoms of any severity.\nAre able to give verbal consent.\nAre 16 years of age or older.\n\nEXCLUSION CRITERIA FOR COVID-19 COHORT:\n\nParticipants with COVID-19 will not be eligible if they:\n\nUse regular prescription eye drops on the day of sampling.\nCurrent use of antiviral medications."]

# After looking at the field values for the Eligibility Criteria split by two new lines, the most common occurences of number of splits were:
# - 4: 950
# - 6: 126
# - 5: 62
# - 8: 59
# -10: 32
def parseCriteria(criteriaString):
    criteria = criteriaString.split("\n\n")
    criteria
    iInclusion = [n for n, l in enumerate(
        criteria) if l.lower().startswith('inclusion')]

    iExclusion = [n for n, l in enumerate(
        criteria) if l.lower().startswith('exclusion')]
    iNon = [n for n, l in enumerate(
        criteria) if l.lower().startswith('non-inclusion')]
    iExclusion = iExclusion + iNon
    iExclusion.sort()

    inclusion = criteria[0:iExclusion[0]]
    exclusion = criteria[iExclusion[0]:]
    obj = {}
    obj = {"criteriaText": criteriaString}
    obj["inclusionCriteria"] = []
    obj["exclusionCriteria"] = []
    for i, foundIdx in enumerate(iInclusion):
        try:
            inclIndices = range(foundIdx, iExclusion[i])
        except:
            inclIndices = range(foundIdx, len(criteria))
        for j in inclIndices:
            splitIncl = criteria[j].split("\n")
            obj["inclusionCriteria"].extend(list(filter(removeInclHeader, splitIncl)))
    for i, foundIdx in enumerate(iExclusion):
        try:
            exclIndices = range(foundIdx, iInclusion[i+1])
        except:
            exclIndices = range(foundIdx, len(criteria))
        for j in exclIndices:
            splitExcl = criteria[j].split("\n")
            obj["exclusionCriteria"].extend(list(filter(removeInclHeader, splitExcl)))
    return(obj)

def removeInclHeader(x):
    return((x.lower() != "inclusion criteria:") & (x.lower() != "inclusion criteria") & (x.lower() != "exclusion criteria:") & (x.lower() != "exclusion criteria") & (x.lower() != "non-inclusion criteria:") & (x.lower() != "non-inclusion criteria"))

x[10].split("\n\n")
parseCriteria(x[10])

# for text in x:
#     parseCriteria(text)

# df = getUSTrials(CT_QUERY, COL_NAMES, False)
# x = df[df["_id"] == "NCT02984761"]["EligibilityModule"].apply(
#     lambda x: x["EligibilityCriteria"])
# x = x.iloc[0]
